Repository nhibernate/fluent-nhibernate, pull requests merged in 2020-09, with the labels that each got.

#379 Implementation for cascade all-delete-orphan for Has-one mapping
  src/FluentNHibernate.Testing/DomainModel/Mapping/CascadeExpressionTester.cs
  src/FluentNHibernate/Mapping/CascadeExpression.cs
  src/FluentNHibernate/Mapping/CollectionCascadeExpression.cs
Labels: improvement

#464 Add Schema property to IJoinedSubclassInspector
  src/FluentNHibernate/Conventions/Inspections/IJoinedSubclassInspector.cs
  src/FluentNHibernate/Conventions/Inspections/JoinedSubclassInspector.cs
  src/FluentNHibernate/Conventions/Instances/IJoinedSubclassInstance.cs
  src/FluentNHibernate/Conventions/Instances/JoinedSubclassInstance.cs
Labels: improvement

#465 Remove invalid cast in ClassInspector.Components
  src/FluentNHibernate/Conventions/Inspections/ClassInspector.cs
Labels: bug

#466 Add Components property to ISubclassInspectorBase
  src/FluentNHibernate/Conventions/Inspections/ISubclassInspectorBase.cs
  src/FluentNHibernate/Conventions/Inspections/JoinedSubclassInspector.cs
  src/FluentNHibernate/Conventions/Inspections/SubclassInspector.cs
Labels: feature

#467 Add join support for Automapping overrides in SubClasses
  src/FluentNHibernate.Specs/Automapping/OverrideSpecs.cs
  src/FluentNHibernate/Automapping/AutoMapping.cs
  src/FluentNHibernate/MappingModel/ClassBased/ClassMappingBase.cs
  src/FluentNHibernate/MappingModel/MappedMembers.cs
Labels: bug

#468 Add KeyColumn override to AutoMapping<>
  src/FluentNHibernate.Testing/AutoMapping/Apm/AutoPersistenceModelTests.Inheritance.cs
  src/FluentNHibernate.Testing/AutoMapping/Apm/AutoPersistenceModelTests.Overrides.cs
  src/FluentNHibernate/Automapping/AutoMapping.cs
  src/FluentNHibernate/Automapping/IAutoClasslike.cs
Labels: api enhancement

#469 Add DiscriminatorValue override to AutoMapping
  src/FluentNHibernate.Testing/AutoMapping/Apm/AutoPersistenceModelTests.Overrides.cs
  src/FluentNHibernate/Automapping/AutoMapping.cs
Labels: api enhancement
